#!/bin/bash

# S3 Deployment Configuration Script
# This script configures your React app for S3 deployment with backend connectivity

set -e

echo "🔧 Configuring React app for S3 deployment..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
S3_BUCKET_NAME="asset-management-react-paramesh"
S3_WEBSITE_URL="http://${S3_BUCKET_NAME}.s3-website-us-east-1.amazonaws.com"

echo -e "${YELLOW}📋 S3 Deployment Configuration:${NC}"
echo "S3 Bucket: $S3_BUCKET_NAME"
echo "S3 Website URL: $S3_WEBSITE_URL"
echo ""

# Get backend URL
echo -e "${YELLOW}📝 Please enter your backend API URL:${NC}"
echo "Examples:"
echo "  - EC2: http://YOUR_EC2_IP:5002/api"
echo "  - Custom domain: https://api.yourdomain.com/api"
echo "  - Load balancer: https://your-load-balancer.com/api"
echo ""
read -p "Backend API URL: " BACKEND_URL

# Ensure URL has protocol
if [[ ! "$BACKEND_URL" =~ ^https?:// ]]; then
    BACKEND_URL="http://$BACKEND_URL"
fi

# Ensure URL has /api suffix
if [[ ! "$BACKEND_URL" =~ /api$ ]]; then
    BACKEND_URL="$BACKEND_URL/api"
fi

echo -e "${GREEN}✅ Using backend URL: $BACKEND_URL${NC}"

# Create production environment file
echo -e "${YELLOW}📝 Creating .env.production file...${NC}"
cat > frontend/.env.production << EOF
# Production Environment Variables for S3 Deployment
# Generated by configure-s3-deployment.sh

# API Configuration
REACT_APP_API_URL=$BACKEND_URL

# Environment
REACT_APP_ENV=production

# Feature Flags
REACT_APP_ENABLE_LOGGING=false
REACT_APP_ENABLE_ANALYTICS=true

# Build Configuration
GENERATE_SOURCEMAP=false
EOF

echo -e "${GREEN}✅ Created frontend/.env.production${NC}"

# Update backend CORS configuration
echo -e "${YELLOW}📝 Updating backend CORS configuration...${NC}"
cat > backend/config.s3.env << EOF
# S3 Deployment Environment Variables
# Copy this to config.env and update with your values

# Database
MONGODB_URI=mongodb+srv://parameshk:tjQR02Mq6Lpdi8O3@cluster1.amnjtnt.mongodb.net/asset_management?retryWrites=true&w=majority&appName=Cluster1

# Server
PORT=5002
NODE_ENV=production

# JWT - CHANGE THIS SECRET FOR PRODUCTION!
JWT_SECRET=your_very_secure_jwt_secret_key_for_production_change_this_to_something_secure
JWT_EXPIRE=24h

# File Upload
MAX_FILE_SIZE=5242880
UPLOAD_PATH=./uploads

# CORS - Allow S3 website
CORS_ORIGIN=$S3_WEBSITE_URL

# Security
BCRYPT_ROUNDS=12
EOF

echo -e "${GREEN}✅ Created backend/config.s3.env${NC}"

# Build the React app
echo -e "${YELLOW}🔨 Building React app for production...${NC}"
cd frontend
npm run build
cd ..

echo -e "${GREEN}✅ React app built successfully${NC}"

# Upload to S3
echo -e "${YELLOW}📤 Uploading to S3...${NC}"
aws s3 sync frontend/build/ s3://$S3_BUCKET_NAME/ --delete

echo -e "${GREEN}✅ Uploaded to S3 successfully${NC}"

echo -e "${GREEN}🎉 S3 deployment configuration completed!${NC}"
echo ""
echo -e "${YELLOW}📝 Summary:${NC}"
echo "Frontend URL: $S3_WEBSITE_URL"
echo "Backend URL: $BACKEND_URL"
echo "CORS configured for: $S3_WEBSITE_URL"
echo ""
echo -e "${YELLOW}📝 Next steps:${NC}"
echo "1. Deploy your backend with the updated CORS configuration"
echo "2. Test the login at: $S3_WEBSITE_URL"
echo "3. Verify API connectivity"
echo ""
echo -e "${YELLOW}📝 Backend deployment:${NC}"
echo "Copy backend/config.s3.env to backend/config.env"
echo "Then deploy your backend with the new CORS settings"
