[build]
command = "cd frontend && npm install && npm run build"
publish = "frontend/build"
base = "."

[build.environment]
NODE_VERSION = "20"
NODE_ENV = "production"
REACT_APP_API_URL = "https://your-render-app.onrender.com/api"
REACT_APP_ENABLE_LOGGING = "false"
REACT_APP_ENABLE_ANALYTICS = "true"
GENERATE_SOURCEMAP = "false"
CI = "false"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
