# Render deployment configuration
services:
  - type: web
    name: asset-management-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://parameshk:tjQR02Mq6Lpdi8O3@cluster1.amnjtnt.mongodb.net/asset_management?retryWrites=true&w=majority&appName=Cluster1
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 24h
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_PATH
        value: ./uploads
      - key: CORS_ORIGIN
        value: https://your-netlify-app.netlify.app
      - key: BCRYPT_ROUNDS
        value: 12
