#!/bin/bash

# React API Configuration Script
# This script sets up your React app with the correct API URL and builds it for deployment

set -e

echo "🔧 Setting up React app API configuration..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get backend URL from user
echo -e "${YELLOW}📝 Enter your backend API URL:${NC}"
echo "Examples:"
echo "  - Local development: http://localhost:5002/api"
echo "  - EC2 deployment: http://YOUR_EC2_IP:5002/api"
echo "  - Custom domain: https://api.yourdomain.com/api"
echo ""
read -p "Backend API URL: " BACKEND_URL

# Ensure URL has protocol
if [[ ! "$BACKEND_URL" =~ ^https?:// ]]; then
    BACKEND_URL="http://$BACKEND_URL"
fi

# Ensure URL has /api suffix
if [[ ! "$BACKEND_URL" =~ /api$ ]]; then
    BACKEND_URL="$BACKEND_URL/api"
fi

echo -e "${GREEN}✅ Using backend URL: $BACKEND_URL${NC}"

# Create development environment file
echo -e "${YELLOW}📝 Creating .env.development...${NC}"
cat > frontend/.env.development << EOF
# Development Environment Variables
# Generated by setup-react-api.sh

# API Configuration
REACT_APP_API_URL=http://localhost:5002/api

# Environment
REACT_APP_ENV=development

# Feature Flags
REACT_APP_ENABLE_LOGGING=true
REACT_APP_ENABLE_ANALYTICS=false

# Build Configuration
GENERATE_SOURCEMAP=true
EOF

# Create production environment file
echo -e "${YELLOW}📝 Creating .env.production...${NC}"
cat > frontend/.env.production << EOF
# Production Environment Variables
# Generated by setup-react-api.sh

# API Configuration
REACT_APP_API_URL=$BACKEND_URL

# Environment
REACT_APP_ENV=production

# Feature Flags
REACT_APP_ENABLE_LOGGING=false
REACT_APP_ENABLE_ANALYTICS=true

# Build Configuration
GENERATE_SOURCEMAP=false
EOF

echo -e "${GREEN}✅ Environment files created${NC}"

# Test the configuration
echo -e "${YELLOW}🧪 Testing API configuration...${NC}"
cd frontend

# Check if the API URL is accessible
if curl -f -s "$BACKEND_URL/health" > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Backend API is accessible at: $BACKEND_URL${NC}"
else
    echo -e "${YELLOW}⚠️  Backend API not accessible at: $BACKEND_URL${NC}"
    echo -e "${YELLOW}📝 Make sure your backend is running before building the frontend${NC}"
fi

# Build the React app
echo -e "${YELLOW}🔨 Building React app for production...${NC}"
npm run build

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ React app built successfully${NC}"
    echo -e "${GREEN}📁 Build files created in: frontend/build/${NC}"
else
    echo -e "${RED}❌ Build failed${NC}"
    exit 1
fi

cd ..

echo -e "${GREEN}🎉 React API configuration completed!${NC}"
echo ""
echo -e "${YELLOW}📝 Summary:${NC}"
echo "Development API URL: http://localhost:5002/api"
echo "Production API URL: $BACKEND_URL"
echo "Build directory: frontend/build/"
echo ""
echo -e "${YELLOW}📝 Next steps:${NC}"
echo "1. Deploy your backend to: $BACKEND_URL"
echo "2. Upload frontend/build/ to S3"
echo "3. Test your application"
echo ""
echo -e "${YELLOW}📝 S3 Upload command:${NC}"
echo "aws s3 sync frontend/build/ s3://asset-management-react-paramesh/ --delete"
